### ISSUE TITLE
Malformed yml file

### ISSUE THREAD

**Issue by AbbyJanke** [OwenMelbz/forget-db#1]
when creating a new config file it is generating a malformed file. It is being generated as such:

```yml
table_one:
    key: user_id
    conditions: ['where user_id != 1', 'or user_email LIKE "%@%"']
    columns: { user_name: name, user_email: email }
table_two:
    key: user_id
    columns: { user_name: name, user_email: email }
table_three:
    key: user_id
    conditions: 'user_id = 1'
    columns: { user_name: name, user_email: email }
```

It is creating an array for conditions.

**Comment by OwenMelbz** [comment]
Hey,

This isn't malformed, it's just an alternative syntax as an example to show how you can use it. 

Try it out on something like http://yaml-online-parser.appspot.com/

Symfony Yaml package is what generates this from an actual array https://github.com/OwenMelbz/forget-db/blob/master/app/Services/UtilityService.php#L97

**Comment by OwenMelbz** [comment]
There is also a test https://github.com/OwenMelbz/forget-db/blob/master/tests/Unit/UtilityTest.php#L41 which uses the generated config and parses it - symfony would throw an error if it was malformed :D

**Comment by AbbyJanke** [comment]
Weird.. When i tried to run it based on the generated file I received a malformed error:

```Madoka:Sites abby$ forget-db forget forgetdb.yml
🧠  forget-db :: Malformed inline YAML string: [ at line 3 (near "conditions: [").
```

when changed to this is ran without issues:
```
clients:
    key: id
    conditions:
      - where id = 18
```

running OS X 10.13.4
