### ISSUE TITLE
[Support] What about JOINS?

### ISSUE THREAD

**Issue by seyfer** [OwenMelbz/forget-db#3]
Very often products have complex connections in their tables.

So, without the support of connections between tables, this library is useful only for simple cases.

**Comment by OwenMelbz** [comment]
Hey @seyfer Joins should be absolutely fine out of the box

As the config file works off table names rather than entities/models you simply just add a definition for your joined table - thats what makes it platform agnostic, it does not need to have any knowledge of your application, simply needs to know a database structure

e.g.

```
users:
  key: user_id
  columns:
    username: unique:username
    email: email

users_addresses:
  key: user_id
  columns:
    line_1: address_street
    line_2: address_city
    state: address_state
```
--

My recommendation would be to try it - and just see if it works, otherwise if you find something it can't actually do then we can look at solving that specific issue?

**Comment by seyfer** [comment]
@OwenMelbz thank you for the answer.
Still, it is not clear. Maybe some documentation can be added?

As I understood
`users_addresses` will join `users` with `addresses` by `user_id` key?
What if I need to join to 3rd table through the 2nd?
Like
accounts -> users -> addresses

So I need
```
UPDATE accounts AS a
INNER JOIN users AS u ON u.acc_id = a.id
INNER JOIN addresses AS ad ON ad.user_id = u.id
SET a.name = null, u.email = null, ad.street = null
WHERE a.id = ?
```

Is it possible? I don't see how.
And what about different JOIN types? LEFT, INNER, etc.

**Comment by OwenMelbz** [comment]
It processes table by table, so it does not need to know about any joins (application/domain logic), it is simply replacing data in a table with anonymous data

If you have 3 tables that you need to have anonymous data within, simply have 3 tables in your config

```
accounts:
  key: account_id
  columns:
    name: name

users:
  key: user_id
  columns:
    email: email

addresses:
  key: address_id
  columns:
    street: streetName
```

**Comment by seyfer** [comment]
@OwenMelbz I see.

In real-world applications common task is not just anonymizing all records, but do it by parameters and by connections with other tables. So, JOINs affect the records set for the anonymization.
This case is not covered.

Is it possible to implement such functionality in this library? WDYT?

**Comment by OwenMelbz** [comment]
You can add conditions to the queries

https://github.com/OwenMelbz/forget-db#configuration

e.g.

```
accounts:
  key: account_id
  conditions:
    - where forget_me = 1
  columns:
    name: name
```

--

I think that you may be over thinking the problem here - maybe if you try it, you will notice that there is not a problem.

By making users define relationships all you're doing is merging multiple tables into 2 config definition, it also then means you need to make the user define the which column is in which table, which then also adds conflicts with naming things etc, which adds extra complexity which is not needed.

--

If you find that it is not actually working, then please let me know - but currently I cannot see a problem you're having. We have used this on various systems such as Magento 2, Wordpress, Laravel, CodeIgnitor, Ruby and .NET - none have had any problems with relationships yet all have been okay!

**Comment by OwenMelbz** [comment]
Closing due to 😕

-- 

If anybody else understands the problem please feel free to explain! Will happily try come up with solutions!

**Comment by seyfer** [comment]
@OwenMelbz because you didn't get the question. 
Simply my SQL query which I provided as an example can't be translated now into the library config. 
The question was if it will be added in the future?

Something like

```
accounts:
  key: account_id
  columns:
    name: name

users:
  key: user_id
  join: accounts
  joinCondition: accounts.id = users.account_id
  columns:
    email: email

addresses:
  key: address_id
  join: users
  joinCondition: users.id = addresses.user_id
  columns:
    street: streetName
  conditions:
    - where account.id = 1
```

That's what is the usual case and required. 

So by account ID we select records VIA connection from user and addresses.

**Comment by OwenMelbz** [comment]
If there is a need to add the functionality, then yes it can be added :) I just need to understand the problem to make sure that an appropriate solution can be put in place.

Would something like this work?

```
accounts:
  key: account_id
  conditions: where id = 1
  columns:
    name: name

users:
  key: user_id
  conditions: where account_id = 1
  columns:
    email: email

addresses:
  key: address_id
  conditions: where user_id = 1
  columns:
    street: streetName
```
