### ISSUE TITLE
Faker-randomFloat

### ISSUE THREAD

**Issue by chynkm** [OwenMelbz/forget-db#6]
Consider the following config.yml file

```
table_one:
    key: user_id
    conditions: ['where user_id != 1', 'or user_email LIKE "%@%"']
    columns: { user_name: name, amount: randomFloat(2, 10, 500) }
```
This file doesn't get processed. The following error is displayed

`🧠  forget-db :: Malformed inline YAML string: { user_name: name, amount: randomFloat(2, 10, 500) } at line 3 (near "columns: { user_name: name, amount: randomFloat(2, 10, 500) }").`

Can you please suggest a solution?
